<a href="https://colab.research.google.com/github/abhicse002/Py_DS_libs/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to define an Numpy Array

In [ ]:
import numpy as np

list1 = [[1,2], [2,3], [4,6]]
nump_arr = np.array(list1)
print(nump_arr)

[[1 2]
 [2 3]
 [4 6]]


# How to Check length, size, datatype and its behavior of len in diff dimension

In [ ]:
l1 = [[[1,2,3,4,5],[1,2,3,4.9,5]], [[1,2,3,4,5],[1,2,3,4,5]], [[1,2,3,4,5],[1,2,3,4,5]]]
l1 = np.array(l1)
print(l1.size) # Gives no. of elements in an Array irrespective of Dimension
print(len(l1)) # Gives the no of elements of 1D Array, no of Rows in 2D array, no of Layers in 3D array
print(l1.dtype)

30
3
float64


In [ ]:
tuple1 = ((1,2), (2,3), (4,9))
nump_arr = np.array(tuple1)
print(nump_arr)

[[1 2]
 [2 3]
 [4 9]]


# How to reshape an Array

In [ ]:
x = np.arange(0, 16)
print(x)

y = x.reshape(2, 8)
print(y)

print(np.shape(y))

y.shape = (4, 4)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]
(2, 8)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# How to create 3D Array
*   shape = (Layers, rows, columns)
*   Repeat 2D array
* Value error will arise if incorrect dimension for incorrect data






In [ ]:
# create an 3D array of 3 layers, 4, rows, 3 columns
# 3 * 4 * 3
x = np.arange(0,36)

x.shape = (3, 4, 3)
print(x)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]

 [[24 25 26]
  [27 28 29]
  [30 31 32]
  [33 34 35]]]


In [ ]:
oned_list = [1,2,3]
twod_list = [[1,2,3], [1,2,3]]
threed_list = [[[1,2,3], [1,2,3]], [[1,2,3], [1,2,3]]]

print(threed_list)
print(np.shape(threed_list))



[[[1, 2, 3], [1, 2, 3]], [[1, 2, 3], [1, 2, 3]]]
(2, 2, 3)


# How to Index & slice np 1D Array

In [ ]:
x = np.arange(0, 16)
# print(x[0:len(x): 2])

# reverse Indexing
print(x[-5: 2: -1])
print(x[-5: -7: -1])
print(x[-5: 0: -1])
print(x[: -3: 1])
# print(x[::])






[11 10  9  8  7  6  5  4  3]
[11 10]
[11 10  9  8  7  6  5  4  3  2  1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


# How to Index np 2D Array

In [ ]:
x = np.arange(0, 16)
x.shape = (4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
x[-1]
x[1][1]
x[1][-1]
x[2][-1]

11

In [ ]:
len(x) # when applied on 2D array returns number of Rows

4

# How to Slice 2D & REVERSE 2D Matrix`

In [ ]:
x = np.arange(0, 16)
x.shape = (4, 4)
# print(x)
print(x[0:4:2,0:4:2])
print(x[::-1])  # reverses ROW
print(x[::-1, ::-1])  # reverses ROW & COLUMN

[[ 0  2]
 [ 8 10]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [ ]:
x = np.arange(0, 16)
x.shape = (4, 4)

print(x)
print(x[3][3])
print(x[::-1])
print(x[::-2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
15
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
[[12 13 14 15]
 [ 4  5  6  7]]


In [ ]:
x = np.arange(0, 16)
x.shape = (4, 4)

print(x[::, :2:]) # first 2 columns
print(x[::, 0:1:]) # first column
print(x[::, -2:-1:1]) # last column

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 2]
 [ 6]
 [10]
 [14]]


In [ ]:
x = np.arange(0, 16)
x.shape = (4, 4)

print(x)
print(x[2::,:2:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 8  9]
 [12 13]]


# Random array generation

In [ ]:
aa = np.random.randint(10, 100, (5, 5))
print(aa)

[[43 31 43 65 85]
 [77 97 42 47 74]
 [99 75 55 53 51]
 [34 65 81 21 40]
 [34 59 43 46 92]]


In [ ]:
# [[22,84][75, 45],[11, 35]]
print(aa[-2:-5:-1,1:3:])

[[22 84]
 [75 34]
 [11 35]]


In [ ]:
# [34]
print(aa[2,2])

34


In [ ]:
# [[79,41][70, 17]]
print(aa[-1:-3:-1,-1:-3:-1])

[[92 46]
 [40 21]]


In [ ]:
# [53 55 75]
print(aa[2:3:, -2:-5:-1])


[[53 55 75]]


In [ ]:
# [[75 55 53]
#  [65 81 21]]

print(aa[-2:-5:-1,-2:-5:-1])

[[21 81 65]
 [53 55 75]
 [47 42 97]]


# How to Slice 3D & REVERSE 3D Matrix`

In [ ]:
three_d_arr = np.random.randint(10, 100, (5, 5, 5))
print(three_d_arr)

[[[60 28 95 81 61]
  [56 81 22 74 15]
  [50 94 83 88 83]
  [13 53 92 71 97]
  [30 66 41 48 74]]

 [[46 64 53 25 10]
  [83 39 19 46 49]
  [94 74 43 89 20]
  [82 38 87 43 72]
  [48 76 85 75 91]]

 [[95 81 16 11 48]
  [48 20 83 23 93]
  [14 39 22 52 68]
  [71 44 88 32 10]
  [32 49 64 89 91]]

 [[32 14 20 33 64]
  [30 30 73 77 22]
  [26 21 14 47 57]
  [82 41 89 58 61]
  [14 20 99 57 48]]

 [[53 10 90 15 68]
  [18 39 24 82 73]
  [54 92 39 98 99]
  [40 95 61 28 72]
  [93 53 46 79 56]]]


In [ ]:
print(three_d_arr[2:3:, 2:3:, 2:3])

[[[22]]]


How to Reshape

In [ ]:
print(three_d_arr.reshape(25, 5))
print(three_d_arr.ravel(25, 5))

[[60 28 95 81 61]
 [56 81 22 74 15]
 [50 94 83 88 83]
 [13 53 92 71 97]
 [30 66 41 48 74]
 [46 64 53 25 10]
 [83 39 19 46 49]
 [94 74 43 89 20]
 [82 38 87 43 72]
 [48 76 85 75 91]
 [95 81 16 11 48]
 [48 20 83 23 93]
 [14 39 22 52 68]
 [71 44 88 32 10]
 [32 49 64 89 91]
 [32 14 20 33 64]
 [30 30 73 77 22]
 [26 21 14 47 57]
 [82 41 89 58 61]
 [14 20 99 57 48]
 [53 10 90 15 68]
 [18 39 24 82 73]
 [54 92 39 98 99]
 [40 95 61 28 72]
 [93 53 46 79 56]]
