<a href="https://colab.research.google.com/github/abhicse002/Py_DS_libs/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How Panda Series & DataFrame differ
1. Series is for 1D, homogenous data, single datatype
2. Dataframe is for 2D, heterogenous data, each column different datatype
3. Each Column is a Series
4. Series created using pd.Series
5. isna & isnull serves the same purpose


In [40]:
import pandas as pd

# Create a DataFrame with custom column names
df = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555], [11111, 22222, 33333, 44444, 55555]],
    columns=['A', 'B', 'C', 'D', 'E'],  # Column names
    index=['A', 'B', 'C', 'D', 'E']  # Column names
)
df1 = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555], [11111, 22222, 33333, 44444, 55555]],
    # columns=[1,2,3,4,5],  # Column names
    # index=[1,2,3,4,5]  # Column names
)

print(df)


       A      B      C      D      E
A     10     20     30     40     50
B     11     22     33     44     55
C    111    222    333    444    555
D   1111   2222   3333   4444   5555
E  11111  22222  33333  44444  55555


# How to fetch using Labels
1. Indexing by Label helps is fetching all Rows but limited columns
Fetches all the Rows but with specified Columns only
2. loc used to fetching using Labelling
3. iloc used to fetch using Indexing (integer positions or integer based indexing)

In [72]:
print(df[['B', 'C']]) # Fetch only multi columns
print("----")
print(df.loc[['A', 'B']])  # fetch only multi Rows
print("----")
print(df.loc[['A', 'C'],['B', 'D']]) # Fetch multi rows & columns

       B      C
A     20     30
B     22     33
C    222    333
D   2222   3333
E  22222  33333
----
    A   B   C   D   E
A  10  20  30  40  50
B  11  22  33  44  55
----
     B    D
A   20   40
C  222  444


In [73]:
print(df1.iloc[2]) # fetch third row and presents it in column format, in a Series
print("----")
print(df1.iloc[[1, 3], [1, 3]]) # fetch group of Rows & Columns using Integer Positioning Indexing
print("----")
print(df1.iloc[2, 3]) # from 3rd Row, fetch 4th Column, index starts from Zero

0    111
1    222
2    333
3    444
4    555
Name: 2, dtype: int64
----
      1     3
1    22    44
3  2222  4444
----
444


# How to fetch using Indexing
Indexing by Integer helps in fetching all Columns with limited Rows
Fethces all the Columns with with Specified Rows only

In [16]:
df[1:3]

A    B    C    D    E
1   11   22   33   44   55
2  111  222  333  444  555

In [24]:
#  shape, size, dtype used for Series
df = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555]],
    columns=['A', 'B', 'C', 'D', 'E']  # Column names
)
print(df.shape) # Number of Rows & Columns
print(df.size) # Number of elements
print(df.index) # gives Index range
print(df.values) # gives only values in Rows & Columns

print(df['A'].name) # gives only values in Rows & Columns
print(df['A'].dtype) # applied on Series

(4, 5)
20
RangeIndex(start=0, stop=4, step=1)
[[  10   20   30   40   50]
 [  11   22   33   44   55]
 [ 111  222  333  444  555]
 [1111 2222 3333 4444 5555]]
A
int64


# How lic & iloc differs
1. loc is slower
2. iloc is faster since position based searching

# How to convert a categorical Columns into a Indicator Variables
1. using get_dummies, knonw as one hot Encoding
2. Creates a new dataframe with columns for each value of categorical variables

In [78]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Gender': ['M', 'F', 'M', 'F', 'F'],
    'Age': [30, 40, 32, 25, 41]
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Use get_dummies to convert 'City' into dummy variables
df_dummies = pd.get_dummies(df, columns=['Gender'], drop_first=False, prefix='G')

# Display the DataFrame with dummy variables
print("\nDataFrame with Dummy Variables:")
print(df_dummies)


Original DataFrame:
  Gender  Age
0      M   30
1      F   40
2      M   32
3      F   25
4      F   41

DataFrame with Dummy Variables:
   Age    G_F    G_M
0   30  False   True
1   40   True  False
2   32  False   True
3   25   True  False
4   41   True  False


# How iterrows()	& nditer diff
1. iterrows used in pandas
2. nditer used in numpy

1. iterows used for row wise iteration, which gives index & Series item
2. nditer iterates thru each & every item