<a href="https://colab.research.google.com/github/abhicse002/Py_DS_libs/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How Panda Series & DataFrame differ
1. Series is for 1D, homogenous data, single datatype
2. Dataframe is for 2D, heterogenous data, each column different datatype
3. Each Column is a Series
4. Series created using pd.Series
5. isna & isnull serves the same purpose


In [ ]:
import pandas as pd

# Create a DataFrame with custom column names
df = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555], [11111, 22222, 33333, 44444, 55555]],
    columns=['A', 'B', 'C', 'D', 'E'],  # Column names
    index=['A', 'B', 'C', 'D', 'E']  # Row names
)
df1 = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555], [11111, 22222, 33333, 44444, 55555]],
    # columns=[1,2,3,4,5],  # Column names
    # index=[1,2,3,4,5]  # Column names
)

print(df)


       A      B      C      D      E
A     10     20     30     40     50
B     11     22     33     44     55
C    111    222    333    444    555
D   1111   2222   3333   4444   5555
E  11111  22222  33333  44444  55555


# How to fetch using Labels
1. Indexing by Label helps is fetching all Rows but limited columns
Fetches all the Rows but with specified Columns only
2. loc used to fetching using Labelling
3. iloc used to fetch using Indexing (integer positions or integer based indexing)

In [ ]:
print(df[['B', 'C']]) # Fetch only multi columns
print("----")
print(df.loc[['A', 'B']])  # fetch only multi Rows
print("----")
print(df.loc[['A', 'C'],['B', 'D']]) # Fetch multi rows & columns

       B      C
A     20     30
B     22     33
C    222    333
D   2222   3333
E  22222  33333
----
    A   B   C   D   E
A  10  20  30  40  50
B  11  22  33  44  55
----
     B    D
A   20   40
C  222  444


In [ ]:
print(df1.iloc[2]) # fetch third row and presents it in column format, in a Series
print("----")
print(df1.iloc[[1, 3], [1, 3]]) # fetch group of Rows & Columns using Integer Positioning Indexing
print("----")
print(df1.iloc[2, 3]) # from 3rd Row, fetch 4th Column, index starts from Zero

0    111
1    222
2    333
3    444
4    555
Name: 2, dtype: int64
----
      1     3
1    22    44
3  2222  4444
----
444


# How to fetch using Indexing
Indexing by Integer helps in fetching all Columns with limited Rows
Fethces all the Columns with with Specified Rows only

In [ ]:
df[1:3]

A    B    C    D    E
1   11   22   33   44   55
2  111  222  333  444  555

In [ ]:
#  shape, size, dtype used for Series
df = pd.DataFrame(
    [[10, 20, 30, 40, 50], [11, 22, 33, 44, 55],[111, 222, 333, 444, 555], [1111, 2222, 3333, 4444, 5555]],
    columns=['A', 'B', 'C', 'D', 'E']  # Column names
)
print(df.shape) # Number of Rows & Columns
print(df.size) # Number of elements
print(df.index) # gives Index range
print(df.values) # gives only values in Rows & Columns

print(df['A'].name) # gives only values in Rows & Columns
print(df['A'].dtype) # applied on Series

(4, 5)
20
RangeIndex(start=0, stop=4, step=1)
[[  10   20   30   40   50]
 [  11   22   33   44   55]
 [ 111  222  333  444  555]
 [1111 2222 3333 4444 5555]]
A
int64


# How lic & iloc differs
1. loc is slower
2. iloc is faster since position based searching

# How to convert a categorical Columns into a Indicator Variables
1. using get_dummies, known as one hot Encoding
2. Creates a new dataframe with columns for each value of categorical variables

In [ ]:
import pandas as pd

# Create a sample DataFrame
data = {
    'Gender': ['M', 'F', 'M', 'F', 'F'],
    'Age': [30, 40, 32, 25, 41]
}

df = pd.DataFrame(data)

# Display the original DataFrame
print("Original DataFrame:")
print(df)

# Use get_dummies to convert 'City' into dummy variables
df_dummies = pd.get_dummies(df, columns=['Gender'], drop_first=False, prefix='G')

# Display the DataFrame with dummy variables
print("\nDataFrame with Dummy Variables:")
print(df_dummies)


Original DataFrame:
  Gender  Age
0      M   30
1      F   40
2      M   32
3      F   25
4      F   41

DataFrame with Dummy Variables:
   Age    G_F    G_M
0   30  False   True
1   40   True  False
2   32  False   True
3   25   True  False
4   41   True  False


2 Types of Object in Pandas
1. Series:- 1D Array, Either Column or Row, indexes and Values.
2. DataFrame:-

# How iterrows()	& nditer diff
1. iterrows used in pandas
2. nditer used in numpy

1. iterows used for row wise iteration, which gives index & Series item
2. nditer iterates thru each & every item

Outlier Capping & Binning difference ..?


count vs size ..?

add() in pandas


# how to modify values in dataframe
- Based on indexes in a dataframe

In [10]:
import pandas as pd

names = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I']
age = [5,4,3,6,7,8,9,8,4]
city = ['AA', 'BB', 'CC', 'DD', 'EE', 'FF', 'GG', 'HH', 'II']
codes = [52,4123,3312,621,7312,128,9231,823, 32]

dict1 = {
    'Names': names,
    'Age': age,
    'City': city,
    'Code': codes
}

df = pd.DataFrame(dict1)
df




Names  Age City  Code
0     A    5   AA    52
1     B    4   BB  4123
2     C    3   CC  3312
3     D    6   DD   621
4     E    7   EE  7312
5     F    8   FF   128
6     G    9   GG  9231
7     H    8   HH   823
8     I    4   II    32

In [11]:
# modify 2nd City
df.iloc[1] # gives second row, ie Index
print(df.iloc[1][-2])

BB


<ipython-input-11-cd680936e2d9>:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.iloc[1][-2])


In [17]:
df.loc[1]['City'] = 'BSDK' # creates in copy if Dataframe rather than original DataFrame

<ipython-input-17-9eb75f6e7a4c>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[1]['City'] = 'BSDK' # creates in copy if Dataframe rather than original DataFrame


In [18]:
df.loc[1, 'City'] = 'BSDK'

In [19]:
df

Names  Age  City  Code
0     A    5    AA    52
1     B    4  BSDK  4123
2     C    3    CC  3312
3     D    6    DD   621
4     E    7    EE  7312
5     F    8    FF   128
6     G    9    GG  9231
7     H    8    HH   823
8     I    4    II    32

In [30]:
df.loc[df.Names == 'H', 'Age'] = 888 # Index , Column , loc to be used with explicit Column (Age)

In [31]:
df


Names  Age  City  Code
0     A    5    AA    52
1     B    4  BSDK  4123
2     C    3    CC  3312
3     D    6    DD   621
4     E    7    EE  7312
5     F    8    FF   128
6     G    9    GG  9231
7     H  888    HH   823
8     I    4    II    32

In [35]:
df
# change city of D to delhi
df.loc[df.Names=='D', 'City'] = 'Delhi'
df

Names  Age   City  Code
0     A    5     AA    52
1     B    4   BSDK  4123
2     C    3     CC  3312
3     D    6  Delhi   621
4     E    7     EE  7312
5     F    8     FF   128
6     G    9     GG  9231
7     H  888     HH   823
8     I    4     II    32

# Importing data from csv

# Important Functions
# Analysis
- groupby
- pivot table
- merging
- sorting
- agg
- condition on DF
# Data transformation
- capping
- Binning
- Encoding


In [36]:
df = pd.read_csv('/content/drive/MyDrive/Woolf/Titanic.csv')
df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [37]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [38]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

# How many Unique Values
1. nunique - applied on both DF & Series , gives count of unique values
2. unique - applied on Series, gives value of unique data points, not the count
3. value_counts - Applied on Series, to find the count of each unique values, not the unique data point values

In [47]:
print(df.nunique())
print(df['PassengerId'].nunique()) # number of unique value columnwise or Series

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64
891


In [58]:
df.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [62]:
# count of unique value in Series
df.Embarked.value_counts() # Doesnt Include Null values
df.Embarked.value_counts(dropna=False)  # Include Null values

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

# How to calculate Percentage of each unique values in columns

In [76]:
print((df.Sex.value_counts(dropna=False, normalize=True))* 100)
print((df.Sex.value_counts(dropna=False)/df.shape[0]) * 100)
print((df.Sex.value_counts(dropna=False)/len(df)) * 100) # use dropna=False to include missing values

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64
Sex
male      64.758698
female    35.241302
Name: count, dtype: float64
Sex
male      64.758698
female    35.241302
Name: count, dtype: float64


In [77]:
df


PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [83]:
df.Fare.mean()
df.mean(numeric_only=True)  # applied on numerical columns, ignoring the Categorical columns

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [94]:
print(df.mode(axis=0).iloc[0]) # gives mode of all columns
print(df.Age.mode().iloc[0]) # gives mode of specific columns

PassengerId                      1
Survived                       0.0
Pclass                         3.0
Name           Abbing, Mr. Anthony
Sex                           male
Age                           24.0
SibSp                          0.0
Parch                          0.0
Ticket                        1601
Fare                          8.05
Cabin                      B96 B98
Embarked                         S
Name: 0, dtype: object
24.0


In [95]:
df.median(numeric_only=True)

PassengerId    446.0000
Survived         0.0000
Pclass           3.0000
Age             28.0000
SibSp            0.0000
Parch            0.0000
Fare            14.4542
dtype: float64

In [102]:
print(df.Age)
print("---------------")
print(df.Age.min())
print(df.Age.max())
print("---------------")
print(df.Fare.sum())
print(df.Fare.sum(numeric_only=True)) # includes only numeric columns
print("---------------")

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64
---------------
0.42
80.0
---------------
28693.9493
28693.9493
---------------


In [106]:
print(df.std(numeric_only=True))
print(df.corr(numeric_only=True))

PassengerId    257.353842
Survived         0.486592
Pclass           0.836071
Age             14.526497
SibSp            1.102743
Parch            0.806057
Fare            49.693429
dtype: float64
             PassengerId  Survived    Pclass       Age     SibSp     Parch  \
PassengerId     1.000000 -0.005007 -0.035144  0.036847 -0.057527 -0.001652   
Survived       -0.005007  1.000000 -0.338481 -0.077221 -0.035322  0.081629   
Pclass         -0.035144 -0.338481  1.000000 -0.369226  0.083081  0.018443   
Age             0.036847 -0.077221 -0.369226  1.000000 -0.308247 -0.189119   
SibSp          -0.057527 -0.035322  0.083081 -0.308247  1.000000  0.414838   
Parch          -0.001652  0.081629  0.018443 -0.189119  0.414838  1.000000   
Fare            0.012658  0.257307 -0.549500  0.096067  0.159651  0.216225   

                 Fare  
PassengerId  0.012658  
Survived     0.257307  
Pclass      -0.549500  
Age          0.096067  
SibSp        0.159651  
Parch        0.216225  
Fare      